// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKMRSf7szMjl_7TNWUNAfYubNSPYau7vI',
    appId: '1:497949764516:web:5fb4b7ed83737e5d00af31',
    messagingSenderId: '497949764516',
    projectId: 'aura-shop-a72a8',
    authDomain: 'aura-shop-a72a8.firebaseapp.com',
    storageBucket: 'aura-shop-a72a8.firebasestorage.app',
    measurementId: 'G-94SWT33QJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYA3rERPMSrPgt9ZVUy0wv8clLYCsgdEk',
    appId: '1:497949764516:android:7e87894c7d1dbc3500af31',
    messagingSenderId: '497949764516',
    projectId: 'aura-shop-a72a8',
    storageBucket: 'aura-shop-a72a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ebPH6ZlLtVf7HeVH4lkp0xAYPwOHFs4',
    appId: '1:497949764516:ios:d4ea0c5a169af4cb00af31',
    messagingSenderId: '497949764516',
    projectId: 'aura-shop-a72a8',
    storageBucket: 'aura-shop-a72a8.firebasestorage.app',
    iosClientId: '497949764516-sha8jabjknqmll5nt082a2ie35iapp63.apps.googleusercontent.com',
    iosBundleId: 'com.example.aurashop',
  );
}
